import fs from "node:fs/promises";
import path from "node:path";

import type {
  ArtifactEdge,
  ArtifactKind,
  ArtifactNode,
  RelationType,
  RepositoryGraph,
  ScanWarning,
} from "./types.js";
import { normalizeRepoPath, stableId, toPosix, uniqueBy } from "./utils.js";

const IGNORED = new Set([".git", ".next", ".turbo", ".cache", "coverage", "dist", "build", "node_modules", "target", "vendor"]);
const TEXT_EXTENSIONS = new Set([
  "", ".cjs", ".css", ".ejs", ".gql", ".graphql", ".hbs", ".html", ".java", ".js", ".json", ".jsx",
  ".md", ".mjs", ".mustache", ".prisma", ".proto", ".py", ".rs", ".sh", ".sol", ".toml", ".ts", ".tsx",
  ".txt", ".xml", ".yaml", ".yml",
]);
const CODE_EXTENSIONS = [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"];
const GENERATED_HEADERS = [/@generated\b/i, /auto[- ]generated/i, /automatically generated/i, /do not edit(?: this file)?/i, /generated by\b/i, /this file is generated/i];
const GENERATED_PATHS = [/(^|\/)__generated__(\/|$)/i, /(^|\/)generated(\/|$)/i, /\.generated\.[^.]+$/i, /(^|\/)gen(\/|$)/i];

interface FileRecord {
  absolutePath: string;
  relativePath: string;
  content: string;
  kind: ArtifactKind;
  generatedEvidence: string[];
}

interface CommandRecord {
  node: ArtifactNode;
  command: string;
  scriptName: string;
  declaredIn: string;
}

export interface ScanOptions {
  maxFiles?: number;
  maxFileBytes?: number;
}

export async function scanRepository(rootInput: string, options: ScanOptions = {}): Promise<RepositoryGraph> {
  const root = path.resolve(rootInput);
  const maxFiles = options.maxFiles ?? 20_000;
  const maxFileBytes = options.maxFileBytes ?? 1_000_000;
  const warnings: ScanWarning[] = [];
  const paths = await walk(root, maxFiles, warnings);
  const generatedAttributes = await loadGeneratedAttributes(root, paths);
  const files: FileRecord[] = [];

  for (const absolutePath of paths) {
    const relativePath = normalizeRepoPath(path.relative(root, absolutePath));
    const stat = await fs.stat(absolutePath);
    if (stat.size > maxFileBytes) {
      warnings.push({ path: relativePath, message: `Skipped file larger than ${maxFileBytes} bytes.` });
      continue;
    }
    if (!looksTextual(relativePath)) continue;
    const content = await readText(absolutePath);
    if (content === null) continue;
    const evidence = detectGeneratedEvidence(relativePath, content, generatedAttributes);
    files.push({
      absolutePath,
      relativePath,
      content,
      generatedEvidence: evidence,
      kind: classifyFile(relativePath, content, evidence.length > 0),
    });
  }

  const repositoryId = toPosix(path.basename(root));
  const nodes: ArtifactNode[] = [];
  const edges: ArtifactEdge[] = [];
  const nodeByPath = new Map<string, ArtifactNode>();
  const edgeKeys = new Set<string>();
  const repositoryNode = makeNode(repositoryId, "repository", repositoryId, "", { root });
  nodes.push(repositoryNode);

  for (const file of files) {
    const node = makeNode(repositoryId, file.kind, path.posix.basename(file.relativePath), file.relativePath,
      file.generatedEvidence.length > 0 ? { generatedEvidence: file.generatedEvidence.join(" | ") } : {});
    nodes.push(node);
    nodeByPath.set(file.relativePath, node);
    addEdge(edges, edgeKeys, repositoryNode, node, "CONTAINS", "Repository scan", 1);
  }

  const commands = discoverPackageCommands(repositoryId, files, nodeByPath, nodes, edges, edgeKeys);
  discoverHeaderLineage(repositoryId, files, nodeByPath, nodes, commands, edges, edgeKeys, warnings);
  discoverKnownConfigs(repositoryId, files, nodeByPath, nodes, commands, edges, edgeKeys);
  discoverImports(files, nodeByPath, edges, edgeKeys);

  const generatedNodes = nodes.filter((node) => node.kind === "generated_file");
  for (const generated of generatedNodes) {
    if (!edges.some((edge) => edge.type === "GENERATES" && edge.to === generated.id)) {
      warnings.push({
        path: generated.path,
        message: "Generated artifact detected, but its authoritative source or generator command could not be resolved.",
      });
    }
  }

  const uniqueNodes = uniqueBy(nodes, (node) => node.id);
  const uniqueEdges = uniqueBy(edges, (edge) => edge.id);
  return {
    repositoryId,
    root,
    nodes: uniqueNodes,
    edges: uniqueEdges,
    warnings,
    stats: {
      files: files.length,
      generatedFiles: generatedNodes.length,
      sourceSpecs: uniqueNodes.filter((node) => node.kind === "source_spec").length,
      commands: uniqueNodes.filter((node) => node.kind === "generator_command").length,
      relationships: uniqueEdges.length,
    },
  };
}

async function walk(root: string, maxFiles: number, warnings: ScanWarning[]): Promise<string[]> {
  const output: string[] = [];
  const queue = [root];
  while (queue.length > 0 && output.length < maxFiles) {
    const current = queue.shift();
    if (!current) break;
    let entries: any[];
    try {
      entries = await fs.readdir(current, { withFileTypes: true, encoding: "utf8" });
    } catch (error) {
      warnings.push({ message: `Could not read ${current}: ${String(error)}` });
      continue;
    }
    entries.sort((a, b) => a.name.localeCompare(b.name));
    for (const entry of entries) {
      if (entry.isSymbolicLink()) continue;
      const absolute = path.join(current, entry.name);
      if (entry.isDirectory()) {
        if (!IGNORED.has(entry.name)) queue.push(absolute);
      } else if (entry.isFile()) {
        output.push(absolute);
        if (output.length >= maxFiles) break;
      }
    }
  }
  if (output.length >= maxFiles) warnings.push({ message: `Repository scan reached the ${maxFiles}-file limit.` });
  return output;
}

async function readText(filePath: string): Promise<string | null> {
  try {
    const value = await fs.readFile(filePath, "utf8");
    return value.includes("\u0000") ? null : value;
  } catch {
    return null;
  }
}

function looksTextual(filePath: string): boolean {
  const base = path.posix.basename(filePath);
  return base.startsWith(".") || TEXT_EXTENSIONS.has(path.posix.extname(filePath).toLowerCase());
}

async function loadGeneratedAttributes(root: string, paths: string[]): Promise<string[]> {
  const attributes = paths.find((candidate) => path.basename(candidate) === ".gitattributes");
  if (!attributes) return [];
  const content = await readText(attributes);
  if (!content) return [];
  return content.split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#") && /linguist-generated(?:=true)?\b/i.test(line))
    .map((line) => normalizeRepoPath(line.split(/\s+/)[0] ?? ""))
    .filter(Boolean)
    .map((pattern) => path.isAbsolute(pattern) ? normalizeRepoPath(path.relative(root, pattern)) : pattern);
}

function detectGeneratedEvidence(filePath: string, content: string, attributes: string[]): string[] {
  const evidence: string[] = [];
  const header = content.split(/\r?\n/).slice(0, 30)
    .filter((line) => /^\s*(?:\/\/|\/\*|\*|#|<!--|;|--)/.test(line))
    .join("\n");
  if (GENERATED_HEADERS.some((pattern) => pattern.test(header))) evidence.push("generated header");
  if (GENERATED_PATHS.some((pattern) => pattern.test(filePath))) evidence.push("generated path");
  if (attributes.some((pattern) => globToRegExp(pattern).test(filePath))) evidence.push(".gitattributes linguist-generated");
  return evidence;
}

function classifyFile(filePath: string, content: string, generated: boolean): ArtifactKind {
  if (generated) return "generated_file";
  if (isTestPath(filePath)) return "test";
  if (isSourceSpec(filePath, content)) return "source_spec";
  if (isGeneratorConfig(filePath, content)) return "generator_config";
  return "file";
}

function isTestPath(filePath: string): boolean {
  return /(^|\/)(?:tests?|__tests__)(\/|$)/i.test(filePath) || /(?:\.test|\.spec)\.[cm]?[jt]sx?$/i.test(filePath);
}

function isSourceSpec(filePath: string, content: string): boolean {
  const lower = filePath.toLowerCase();
  return /(^|\/)(?:openapi|swagger)\.(?:ya?ml|json)$/.test(lower)
    || /\.(?:graphql|gql|proto|prisma)$/.test(lower)
    || (/\.(?:ya?ml|json)$/.test(lower) && /\bopenapi\s*[:"]|\bswagger\s*[:"]/i.test(content));
}

function isGeneratorConfig(filePath: string, content: string): boolean {
  const lower = filePath.toLowerCase();
  return /(^|\/)(?:codegen\.(?:ya?ml|json)|orval\.config\.[cm]?[jt]s|buf\.gen\.ya?ml)$/.test(lower)
    || (/package\.json$/.test(lower) && /(?:codegen|generate|openapi|orval|prisma|buf)/i.test(content));
}

function discoverPackageCommands(
  repositoryId: string,
  files: FileRecord[],
  nodeByPath: Map<string, ArtifactNode>,
  nodes: ArtifactNode[],
  edges: ArtifactEdge[],
  edgeKeys: Set<string>,
): CommandRecord[] {
  const commands: CommandRecord[] = [];
  for (const file of files.filter((candidate) => path.posix.basename(candidate.relativePath) === "package.json")) {
    let parsed: any;
    try { parsed = JSON.parse(file.content); } catch { continue; }
    const scripts = parsed?.scripts;
    if (!scripts || typeof scripts !== "object") continue;
    const declaration = nodeByPath.get(file.relativePath);
    if (!declaration) continue;
    for (const [name, value] of Object.entries(scripts)) {
      if (typeof value !== "string" || !/(?:codegen|generate|openapi|swagger|orval|prisma\s+generate|buf\s+generate|protoc|typechain)/i.test(`${name} ${value}`)) continue;
      const run = `npm run ${name}`;
      const node = makeNode(repositoryId, "generator_command", name, `${file.relativePath}#script:${name}`, {
        run, command: value, scriptName: name, declaredIn: file.relativePath,
      });
      nodes.push(node);
      commands.push({ node, command: value, scriptName: name, declaredIn: file.relativePath });
      addEdge(edges, edgeKeys, declaration, node, "DECLARES", `${file.relativePath} declares ${name}`, 1);
    }
  }
  return commands;
}

function discoverHeaderLineage(
  repositoryId: string,
  files: FileRecord[],
  nodeByPath: Map<string, ArtifactNode>,
  nodes: ArtifactNode[],
  commands: CommandRecord[],
  edges: ArtifactEdge[],
  edgeKeys: Set<string>,
  warnings: ScanWarning[],
): void {
  for (const file of files.filter((candidate) => candidate.kind === "generated_file")) {
    const target = nodeByPath.get(file.relativePath);
    if (!target) continue;
    const header = file.content.split(/\r?\n/).slice(0, 30).join("\n");
    const sourceHints = captures(header, /(?:@source|source|schema)\s*:\s*["'`]?([^"'`\s*]+)["'`]?/gi);
    const commandHints = captures(header, /(?:command|regenerate(?:\s+with)?)\s*:\s*([^\n*]+)/gi).map((value) => value.trim());
    for (const sourceHint of sourceHints) {
      const sourcePath = resolveHint(file.relativePath, sourceHint, nodeByPath);
      const source = sourcePath ? nodeByPath.get(sourcePath) : undefined;
      if (!source) {
        warnings.push({ path: file.relativePath, message: `Header source hint could not be resolved: ${sourceHint}` });
        continue;
      }
      if (source.kind === "file" && isSourceSpec(source.path, "")) source.kind = "source_spec";
      const hint = commandHints[0];
      let command = commands.find((candidate) => hint && (
        candidate.command.toLowerCase().includes(hint.toLowerCase()) ||
        hint.toLowerCase().includes(candidate.scriptName.toLowerCase()) ||
        hint.toLowerCase().includes(`npm run ${candidate.scriptName}`.toLowerCase())
      ));
      if (!command) command = commands[0];
      if (!command) {
        const text = hint ?? `regenerate ${file.relativePath}`;
        const commandNode = makeNode(repositoryId, "generator_command", text, `${file.relativePath}#header-command`, {
          run: text, command: text, inferredFrom: file.relativePath,
        });
        nodes.push(commandNode);
        command = { node: commandNode, command: text, scriptName: text, declaredIn: file.relativePath };
        commands.push(command);
      }
      addEdge(edges, edgeKeys, source, command.node, "FEEDS", `Generated-file header names ${sourceHint}`, .99);
      addEdge(edges, edgeKeys, command.node, target, "GENERATES", "Generated-file header provides provenance", .99);
    }
  }
}

function discoverKnownConfigs(
  _repositoryId: string,
  files: FileRecord[],
  nodeByPath: Map<string, ArtifactNode>,
  _nodes: ArtifactNode[],
  commands: CommandRecord[],
  edges: ArtifactEdge[],
  edgeKeys: Set<string>,
): void {
  for (const file of files.filter((candidate) => candidate.kind === "generator_config" && path.posix.basename(candidate.relativePath) !== "package.json")) {
    const configNode = nodeByPath.get(file.relativePath);
    if (!configNode) continue;
    const command = commands.find((candidate) => toolMatches(file.relativePath, candidate.command));
    if (command) addEdge(edges, edgeKeys, configNode, command.node, "DECLARES", `${file.relativePath} configures generation`, .9);
  }
}

function toolMatches(configPath: string, command: string): boolean {
  const lower = `${configPath} ${command}`.toLowerCase();
  return ["codegen", "orval", "buf", "prisma", "openapi"].some((tool) => lower.includes(tool));
}

function discoverImports(files: FileRecord[], nodeByPath: Map<string, ArtifactNode>, edges: ArtifactEdge[], edgeKeys: Set<string>): void {
  for (const file of files.filter((candidate) => CODE_EXTENSIONS.includes(path.posix.extname(candidate.relativePath)))) {
    const source = nodeByPath.get(file.relativePath);
    if (!source) continue;
    const specifiers = new Set([
      ...captures(file.content, /\bimport\s+(?:type\s+)?(?:[\s\S]*?\s+from\s+)?["'`]([^"'`]+)["'`]/g),
      ...captures(file.content, /\brequire\(\s*["'`]([^"'`]+)["'`]\s*\)/g),
      ...captures(file.content, /\bimport\(\s*["'`]([^"'`]+)["'`]\s*\)/g),
    ]);
    for (const specifier of specifiers) {
      const target = resolveImport(file.relativePath, specifier, nodeByPath);
      if (!target) continue;
      addEdge(edges, edgeKeys, source, target, "IMPORTS", `${file.relativePath} imports ${specifier}`, .94);
      if (source.kind === "test") addEdge(edges, edgeKeys, source, target, "VERIFIES", `${file.relativePath} directly exercises imported code`, .82);
    }
  }
}

function resolveImport(importer: string, specifier: string, nodeByPath: Map<string, ArtifactNode>): ArtifactNode | undefined {
  if (!specifier.startsWith(".")) return undefined;
  const base = normalizeRepoPath(path.posix.join(path.posix.dirname(importer), specifier));
  for (const candidate of [base, ...CODE_EXTENSIONS.map((ext) => `${base}${ext}`), ...CODE_EXTENSIONS.map((ext) => `${base}/index${ext}`)]) {
    const node = nodeByPath.get(normalizeRepoPath(candidate));
    if (node) return node;
  }
  return undefined;
}

function resolveHint(generatedPath: string, hint: string, nodeByPath: Map<string, ArtifactNode>): string | undefined {
  const normalized = normalizeRepoPath(hint.replace(/^file:/, "").replace(/^["']|["']$/g, ""));
  const candidates = [
    normalized,
    normalizeRepoPath(path.posix.join(path.posix.dirname(generatedPath), normalized)),
    normalizeRepoPath(path.posix.join(path.posix.dirname(generatedPath), "..", normalized)),
    normalizeRepoPath(path.posix.join(path.posix.dirname(generatedPath), "../..", normalized)),
  ];
  return candidates.find((candidate) => nodeByPath.has(candidate));
}

function makeNode(repositoryId: string, kind: ArtifactKind, name: string, nodePath: string, metadata: Record<string, string | number | boolean>): ArtifactNode {
  const key = `${repositoryId}:${kind}:${nodePath || name}`;
  return { id: stableId(key), key, kind, name, path: nodePath, metadata };
}

function addEdge(
  edges: ArtifactEdge[], edgeKeys: Set<string>, from: ArtifactNode, to: ArtifactNode,
  type: RelationType, evidence: string, confidence: number,
): void {
  const key = `${type}:${from.id}:${to.id}`;
  if (edgeKeys.has(key)) return;
  edgeKeys.add(key);
  edges.push({ id: stableId(key), from: from.id, to: to.id, type, evidence, confidence });
}

function captures(content: string, regex: RegExp): string[] {
  const values: string[] = [];
  for (const match of content.matchAll(regex)) if (match[1]) values.push(match[1].trim());
  return values;
}

function globToRegExp(glob: string): RegExp {
  const escaped = glob.replace(/[.+^${}()|[\]\\]/g, "\\$&")
    .replace(/\*\*/g, "::DOUBLE_STAR::")
    .replace(/\*/g, "[^/]*")
    .replace(/::DOUBLE_STAR::/g, ".*")
    .replace(/\?/g, ".");
  return new RegExp(`^${escaped}$`);
}
